config/routes.rb
Rails.application.routes.draw do

  devise_for :users
	root "posts#index"

	resources :posts do
		resources :comments
		member do
			put "like" => "posts#upvote"
			put "unlike" => "posts#downvote"
		
	end
end


	get '/home', to: 'posts#home'
	get '/posts/:id/:title' => 'posts#show', :as => :post_with_title
	get '/about', to: 'pages#about'

	resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
	acts_as_votable
	has_attached_file :image, styles: { large: "600x600>", medium: "300x300>", thumb: "150x150#"}
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
	validates :title, presence: true, length: { maximum: 30 }
	validates :description, presence: true, length: { minimum: 5 }
	attr_accessor :delete_image
	belongs_to :user
	has_many :comments
	before_validation { image.clear if delete_image == '1' }

end


def delete_image
	@delete_image ||= false
end

def delete_image(value)
	@delete_image = !value.to_i.zero?
end

app/models/user.rb
class User < ApplicationRecord
	acts_as_voter
	has_many :posts
	has_many :comments

	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :find_post
	before_action :find_comment, only: [:edit, :update, :destroy]
	before_action :authenticate_user!

	def create
		@comment = @post.comments.create(comment_params)
		@comment.user_id = current_user.id

		if @comment.save
			redirect_to post_path(@post)
		else
			flash[:alert] = "Komentarz nie może być pusty!"
			redirect_to post_path(@post)
		end
	end

	def edit
	end

	def update
		if @comment.update(comment_params)
			redirect_to post_path(@post)
		else
			render 'edit'
		end
	end

	def destroy
		@comment.destroy
		redirect_to post_path(@post)
	end


	private

		def comment_params
			params.require(:comment).permit(:content)
		end

		def find_post
			@post = Post.find(params[:post_id])
		end

		def find_comment
			@comment = @post.comments.find(params[:id])			
		end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def about
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_filter :authenticate_user!, except: [:index, :home, :show]
	before_action :find_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote]

	def index
	end

	def home
		@posts = Post.reorder("created_at DESC").page(params[:page]).per_page(4)
	end

	def show
	end

	def new
		@post = current_user.posts.build
	end

	def create
		@post = current_user.posts.build(post_params)
		if @post.save
			redirect_to home_path
		else
			render 'new'
		end
	end

	def edit
		unless current_user == @post.user
			redirect_to(@post, notice: "Nie możesz edytować tego postu")
		end
	end

	def update
		if @post.update(post_params)
			redirect_to post_path
		else
			render 'edit'
		end
	end

	def destroy
		if @post.destroy
			redirect_to home_path
		end
	end

	def upvote
		@post.upvote_from current_user
		redirect_to post_path
	end

	def downvote
		@post.downvote_from current_user
		redirect_to post_path		
	end

	private

		def post_params
			params.require(:post).permit(:title, :description, :image, :delete_image)
		end

		def find_post
			@post = Post.find(params[:id])
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
	@user = User.find(params[:id])
	@user_posts = @user.posts
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<strong><p class="post-posted-by">Utworzone przez <%= comment.user.email %> <%=time_ago_in_words(comment.created_at) %> ago</p></strong>
	<p><%= comment.content %></p>
	<% if user_signed_in? %>
	<% if comment.user_id == current_user.id %>
	<%= link_to "Edytuj", edit_post_comment_path(comment.post, comment), class: "btn btn-default" %>
	<%= link_to "Usuń", post_comment_path(comment.post, comment), method: :delete, data: { confirm: "Na pewno chcesz usunąć komentarz?"}, class: "btn btn-default"  %>
	<% end %>
	<% end %>
<hr>

app/views/comments/_form.html.erb
<%= simple_form_for([@post, @post.comments.build]) do |f| %>
	<%= f.input :content, label: "Komentarz" %>
	<%= f.button :submit, 'Dodaj Komentarz' %>
<% end %>


<%= render 'posts/alerts' %>

app/views/comments/edit.html.erb
<div class="container text-center">
	<div class="col-md-8 col-md-offset-2">
		<h1 class="new-post-header">Edytuj komentarz</h1>
			<%= simple_form_for([@post, @comment]) do |f| %>
			<%= f.input :content, label: "Komentarz" %>
			<%= f.button :submit, 'Aktualizuj' %>
		<% end %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Motocross</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

	<nav class="navbar navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<strong><%= link_to "Motocross", root_path, class: "navbar-brand" %></strong>
		  </div>
			 <ul class="navbar-nav nav">
				  <li><%= link_to "Zarejestruj", new_user_registration_path %></li>
				<% if user_signed_in? %>
					<li><%= link_to "Wyloguj", destroy_user_session_path, method: :delete %></li>
          <li><%= link_to current_user.email, current_user %></li>
				<% else %>	
					<li><%= link_to "Zaloguj", new_user_session_path %></li>
				<% end %>
       </ul>
       <ul class="navbar-nav nav pull-right"> 
        <li><%= link_to "Posty", home_path %></li>
				<li><%= link_to "Nowy Post", new_post_path %></li>
			 </ul>
		</div>
	</nav>     

  <nav class="navbar navbar-fixed-bottom">
    <div class="container">
      <br/>
      <p class="text-center fa-1x">
        <a target="_blank" href="https://github.com/kondziqq17" style="color:#000000">
          <%= icon("github-square fa-2x") %>
        <a target="_blank" href="https://pl.linkedin.com/in/konrad-pasoń-a3bb6b116" style="color:#000000">
          <%= icon("linkedin-square fa-2x") %>
        <a href="/about" style="color:#000000">
          <%= icon("fa fa-info-circle fa-2x") %>
        </a>
      </p>
    </div>
  </nav>

    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container center">
	<div id="page_wrapper">
	 	<div id="profile_image">
	 		<%= image_tag "ja.jpg" %>
		</div>
		<div class="content">
		 	<h2>Hey, I'm Konrad Pasoń</h2>
		 		<p>Welcome to my Website</p>
		 		<p>If you'd like to follow along as I learn more Ruby on Rails, find me on GitHub <a target="_blank" href="https://github.com/kondziqq17">kondziqq17</a> or on the <a target="_blank" href="https://pl.linkedin.com/in/konrad-pasoń-a3bb6b116">LinkedIn</a>. Also if you want to be in touch, you can email me at <a target="_blank" href="mailto:konrad.pason17@gmail.com">konrad.pason17@gmail.com</a>.</p>
				
				<%= link_to "Wróc", root_path, class: "btn btn-default" %>
		</div>
	</div>
</div>	

app/views/posts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/posts/_form.html.erb
<%= simple_form_for @post, html: { multipart: true } do |f| %><br/>
<% if @post.image.exists? %>
	<%= image_tag @post.image.url(:thumb) %><br/>
	<%= f.check_box :delete_image %>Usuń Zdjęcie<br/>
<% end %>
  <%= f.file_field :image %>
  <%= f.input :title, label: "Tytuł" %>
  <%= f.input :description, label: "Opis" %>
  <%= f.button :submit, 'Utwórz'  %>
<% end %>

app/views/posts/edit.html.erb
<div class="container text-center">
	<div class="col-md-8 col-md-offset-2">
		<h1 class="new-post-header">Edytuj Post</h1>
			<%= render 'form' %>
			<%= link_to "Wróć", home_path, class: "btn btn-default" %>
	</div>
</div>

app/views/posts/home.html.erb
<div class="container">
	<div class="row">
		<h2 class="text-center">Posty</h2>
<hr>
<% @posts.each do |post| %>
	<div class="col-md-6 col-md-3 text-center">
		<div class="post">
			<a href="/posts/<%= post.id %>">
				<h2><%= link_to post.title, post_with_title_path(post, :title => post.title) %></h2>
				<% if post.image.file? %>
					<%= image_tag(post.image, size: "250x250") %>
				<% else %>
						Brak Zdjęcia
				<% end %>
			</a>
		</div>	
	</div>
<% end %>
</div>
</div>

<div class="container text-center">
	<div class="col-md-8 col-md-offset-2">
		<div class="pagination">	
			<%= will_paginate @post, renderer: BootstrapPagination::Rails %><br>
			<%= link_to "Wróć", root_path, class: "btn btn-default" %>
		</div>
	</div>	
</div>
<br/>
<br/>		

app/views/posts/index.html.erb
<div class="jumbotron text-center">
	<h1>Motocross</h1>
	  <p>Witam, by wyświetlić posty kliknij <%= link_to "Tutaj", home_path, :style=>'color:#00BFFF;' %> </p>
	  <p>Zalogować się, kliknij <%= link_to "Tutaj", new_user_session_path, :style=>'color:	#7CFC00;' %> </p>
	  <p>Dodać post, kliknij <%= link_to "Tutaj", new_post_path, :style=>'color: #FF4C00;' %> </p>
</div>

<div class="container" id="main-container">
	<div class="row">
		<div class="col-sm-4">
			<h1 class="text-center"><i class="fa fa-indent homepage-icon"></i></h1>
				<p class="text-center">Zobacz posty różnych użytkowników</p>
		</div>

		<div class="col-sm-4">
			<h1 class="text-center"><i class="fa fa-picture-o  homepage-icon"></i></h1>
				<p class="text-center">Dodawaj posty oraz zdjęcia</p>
		</div>

		<div class="col-sm-4">
			<h1 class="text-center"><i class="fa fa-thumbs-up homepage-icon"></i></h1>
				<p class="text-center">Funkcja Like dla każdego postu</p>
		</div>
	</div>
</div>
<%= render 'alerts' %>

app/views/posts/new.html.erb
<div class="container text-center">
	<div class="col-md-8 col-md-offset-2">
		<h2>Nowy Post</h2>
		<hr>
			<%= render 'form' %>
			<%= link_to "Wróć", root_path, class: "btn btn-default" %>
	</div>
</div>

app/views/posts/show.html.erb
<br/>
<div class="container">
	<div class="col-md-8 col-md-offset-2">
		<div class="post-show">
			<h2><%= @post.title %></h2>
				<p class="post-posted-by">Utworzone przez <%= @post.user.email %> <%= time_ago_in_words(@post.created_at) %> ago</p>
				<p class="post-desc"><%= @post.description %></p><hr>
					<% if @post.image.file? %>
						<%= image_tag @post.image.url(:large), :class => "style_image" %>
					<% else %>
						<h2 class="text-center">Brak Zdjęcia</h2>
					<% end %>
					<br/>


				<h3>Komentarze</h3>
					<%= render @post.comments %>

				<h3>Zostaw Komentarz</h3>
					<%= render 'comments/form' %>
				
			<div class="caption" style="text-align:left;">
				<%= link_to like_post_path(@post), class: "like", method: :put do %>
				<button type="button" class="btn btn-primary" aria-label="Left Align">
				<span class="fa fa-thumbs-up fa-align-left" aria-hidden="true"></span>
				<span class="badge"><%= @post.get_upvotes.size %></span>
				</button>
				<% end %>


				<%= link_to unlike_post_path(@post), class: "unlike", method: :put do %>
				<button type="button" class="btn btn-danger" aria-label="Left Align">
				<span class="fa fa-thumbs-down fa-align-left" aria-hidden="true"></span>
				<span class="badge"><%= @post.get_downvotes.size %></span>
				</button>
				<% end %>
				</div><br>

				<div class="links btn-group">
					<%= link_to "Wróć", home_path, class: "btn btn-default" %>
						<% if user_signed_in? %>
							<% if @post.user_id == current_user.id %>
								<%= link_to "Edytuj", edit_post_path(@post), class: "btn btn-default" %>
								<%= link_to "Usuń", post_path(@post), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default" %>
								<% end %>
									<% end %>
				</div>
			</div>
		</div>
	</div>
</div>


<%= render 'alerts' %>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<h2 class="text-center"><%= @user.email %></h2><hr>
			<% @user_posts.each do |post| %>
				<div class="col-md-6 col-md-3 text-center">
					<div class="post">
						<a href="/posts/<%= post.id %>">
							<h2><%= link_to post.title, post_with_title_path(post, :title => post.title) %></h2>
							<% if post.image.file? %>
								<%= image_tag(post.image, size: "250x250") %>
							<% else %>
								Brak Zdjęcia
							<% end %>
						</a>
					</div>	
				</div>
			<% end %>
	</div>
</div>

<div class="container text-center">
	<div class="col-md-8 col-md-offset-2">
		<%= link_to "Wróć", root_path, class: "btn btn-default" %>
	</div>
</div>
<br/>
<br/>
<br/>